// +build !noasm !appengine
// Code generated by asm2asm, DO NOT EDIT.

package base64x

import (
    `unsafe`
)

//go:nosplit
//go:noescape
//goland:noinspection ALL
func ___asm2asm_compiled_code__DO_NOT_CALL_THIS_SYMBOL___()

var (
    _func__base      = ___asm2asm_compiled_code__DO_NOT_CALL_THIS_SYMBOL___
    _subr__b64decode = **(**uintptr)(unsafe.Pointer(&_func__base)) + 1447
    _subr__b64encode = **(**uintptr)(unsafe.Pointer(&_func__base)) + 224
)

var (
    _ = _subr__b64decode
    _ = _subr__b64encode
)
