// +build !noasm !appengine
// Code generated by nocgo, DO NOT EDIT.

#include "go_asm.h"
#include "funcdata.h"
#include "textflag.h"

TEXT ·__native_entry__(SB), NOSPLIT, $0
	NO_LOCAL_POINTERS
	PCALIGN $2048
	WORD    $0x10000000 // adr	x0, 0
	WORD    $0xf90007e0 // str	x0, [sp, #8]
	WORD    $0xd65f03c0 // ret

	// _b64encode:
	WORD $0xf9400429 // ldr	x9, [x1, #8]
	WORD $0xb4000c09 // cbz	x9, 400 // LBB0_17
	WORD $0xa9402808 // ldp	x8, x10, [x0]
	WORD $0x8b0a0108 // add	x8, x8, x10
	WORD $0xf940002b // ldr	x11, [x1]
	WORD $0x8b09016c // add	x12, x11, x9
	WORD $0x90000009 // adrp	x9, 0 // _TabEncodeCharsetURL
	WORD $0x91282129 // add	x9, x9, 2568 // _TabEncodeCharsetURL
	WORD $0x9000000a // adrp	x10, 0 // _TabEncodeCharsetStd
	WORD $0x9127214a // add	x10, x10, 2504 // _TabEncodeCharsetStd
	WORD $0x7200005f // tst	w2, #0x1
	WORD $0x9a89014a // csel	x10, x10, x9, eq
	WORD $0xd100118d // sub	x13, x12, #4
	WORD $0xeb0d017f // cmp	x11, x13
	WORD $0x54000069 // b.ls	80 // LBB0_3
	WORD $0xaa0803e9 // mov	x9, x8
	WORD $0x14000014 // b	156 // LBB0_5

	// LBB0_3:
	WORD $0xaa0803ee // mov	x14, x8

	// LBB0_4:
	WORD $0xb8403569 // ldr	w9, [x11], #3
	WORD $0x5ac00929 // rev	w9, w9
	WORD $0xd35afd2f // lsr	x15, x9, #26
	WORD $0xd3546530 // ubfx	x16, x9, #20, #6
	WORD $0xd34e4d31 // ubfx	x17, x9, #14, #6
	WORD $0xd3483529 // ubfx	x9, x9, #8, #6
	WORD $0x386f694f // ldrb	w15, [x10, x15]
	WORD $0x390001cf // strb	w15, [x14]
	WORD $0x3870694f // ldrb	w15, [x10, x16]
	WORD $0x390005cf // strb	w15, [x14, #1]
	WORD $0x3871694f // ldrb	w15, [x10, x17]
	WORD $0x390009cf // strb	w15, [x14, #2]
	WORD $0x3869694f // ldrb	w15, [x10, x9]
	WORD $0x910011c9 // add	x9, x14, #4
	WORD $0x39000dcf // strb	w15, [x14, #3]
	WORD $0xaa0903ee // mov	x14, x9
	WORD $0xeb0d017f // cmp	x11, x13
	WORD $0x54fffde9 // b.ls	84 // LBB0_4

	// LBB0_5:
	WORD $0xcb0b018e // sub	x14, x12, x11
	WORD $0x3940016c // ldrb	w12, [x11]
	WORD $0xf10005df // cmp	x14, #1
	WORD $0x540004e0 // b.eq	324 // LBB0_11
	WORD $0xd370bd8d // lsl	x13, x12, #16
	WORD $0xf10009df // cmp	x14, #2
	WORD $0x54000280 // b.eq	260 // LBB0_9
	WORD $0xf1000ddf // cmp	x14, #3
	WORD $0x54000621 // b.ne	384 // LBB0_16
	WORD $0x3940096e // ldrb	w14, [x11, #2]
	WORD $0xaa0e01ad // orr	x13, x13, x14
	WORD $0x3940056b // ldrb	w11, [x11, #1]
	WORD $0xaa0b21ab // orr	x11, x13, x11, lsl #8
	WORD $0xd34c456d // ubfx	x13, x11, #12, #6
	WORD $0xd342fd8c // lsr	x12, x12, #2
	WORD $0x386c694c // ldrb	w12, [x10, x12]
	WORD $0x386d694d // ldrb	w13, [x10, x13]
	WORD $0x3900012c // strb	w12, [x9]
	WORD $0x3900052d // strb	w13, [x9, #1]
	WORD $0xd3462d6b // ubfx	x11, x11, #6, #6
	WORD $0x386b694b // ldrb	w11, [x10, x11]
	WORD $0x3900092b // strb	w11, [x9, #2]
	WORD $0x924015cb // and	x11, x14, #0x3f
	WORD $0x386b694a // ldrb	w10, [x10, x11]
	WORD $0x39000d2a // strb	w10, [x9, #3]
	WORD $0x1400001b // b	364 // LBB0_13

	// LBB0_9:
	WORD $0x3940056b // ldrb	w11, [x11, #1]
	WORD $0x2a0b21ad // orr	w13, w13, w11, lsl #8
	WORD $0xd342fd8c // lsr	x12, x12, #2
	WORD $0x386c694c // ldrb	w12, [x10, x12]
	WORD $0x3900012c // strb	w12, [x9]
	WORD $0xd34c45ac // ubfx	x12, x13, #12, #6
	WORD $0x386c694c // ldrb	w12, [x10, x12]
	WORD $0x3900052c // strb	w12, [x9, #1]
	WORD $0x531e756b // lsl	w11, w11, #2
	WORD $0x927e0d6b // and	x11, x11, #0x3c
	WORD $0x386b694a // ldrb	w10, [x10, x11]
	WORD $0x3900092a // strb	w10, [x9, #2]
	WORD $0x37080202 // tbnz	w2, #1, 372 // LBB0_14
	WORD $0x528007aa // mov	w10, #61
	WORD $0x39000d2a // strb	w10, [x9, #3]
	WORD $0x1400000b // b	364 // LBB0_13

	// LBB0_11:
	WORD $0xd342fd8b // lsr	x11, x12, #2
	WORD $0x386b694b // ldrb	w11, [x10, x11]
	WORD $0x3900012b // strb	w11, [x9]
	WORD $0x531c6d8b // lsl	w11, w12, #4
	WORD $0x927c056b // and	x11, x11, #0x30
	WORD $0x386b694a // ldrb	w10, [x10, x11]
	WORD $0x3900052a // strb	w10, [x9, #1]
	WORD $0x370800e2 // tbnz	w2, #1, 380 // LBB0_15
	WORD $0x5287a7aa // mov	w10, #15677
	WORD $0x7900052a // strh	w10, [x9, #2]

	// LBB0_13:
	WORD $0x91001129 // add	x9, x9, #4
	WORD $0x14000004 // b	384 // LBB0_16

	// LBB0_14:
	WORD $0x91000d29 // add	x9, x9, #3
	WORD $0x14000002 // b	384 // LBB0_16

	// LBB0_15:
	WORD $0x91000929 // add	x9, x9, #2

	// LBB0_16:
	WORD $0xf940040a // ldr	x10, [x0, #8]
	WORD $0xcb080128 // sub	x8, x9, x8
	WORD $0x8b0a0108 // add	x8, x8, x10
	WORD $0xf9000408 // str	x8, [x0, #8]

	// LBB0_17:
	WORD $0xd65f03c0 // ret

	// _b64decode:
	WORD $0xa9bd5ff8 // stp	x24, x23, [sp, #-48]!
	WORD $0xa90157f6 // stp	x22, x21, [sp, #16]
	WORD $0xa9024ff4 // stp	x20, x19, [sp, #32]
	WORD $0xb4001642 // cbz	x2, 1128 // LBB1_42
	WORD $0xa9402009 // ldp	x9, x8, [x0]
	WORD $0x8b080128 // add	x8, x9, x8
	WORD $0xf940080a // ldr	x10, [x0, #16]
	WORD $0x8b0a012f // add	x15, x9, x10
	WORD $0x8b020029 // add	x9, x1, x2
	WORD $0x9000000a // adrp	x10, 0 // _VecDecodeCharsetURL
	WORD $0x912d214a // add	x10, x10, 2888 // _VecDecodeCharsetURL
	WORD $0x9000000b // adrp	x11, 0 // _VecDecodeCharsetStd
	WORD $0x9129216b // add	x11, x11, 2632 // _VecDecodeCharsetStd
	WORD $0x7200007f // tst	w3, #0x1
	WORD $0x9a8a016a // csel	x10, x11, x10, eq
	WORD $0xd1002130 // sub	x16, x9, #8
	WORD $0xd100052b // sub	x11, x9, #1
	WORD $0x9100052e // add	x14, x9, #1
	WORD $0xeb01021f // cmp	x16, x1
	WORD $0x54001503 // b.lo	1152 // LBB1_43
	WORD $0xd10021f1 // sub	x17, x15, #8
	WORD $0xeb11011f // cmp	x8, x17
	WORD $0x540014a8 // b.hi	1152 // LBB1_43
	WORD $0x52800082 // mov	w2, #4
	WORD $0xaa0103ed // mov	x13, x1
	WORD $0xaa0803ec // mov	x12, x8

	// LBB1_4:
	WORD $0x394001a7 // ldrb	w7, [x13]
	WORD $0x38676944 // ldrb	w4, [x10, x7]
	WORD $0x394005a5 // ldrb	w5, [x13, #1]
	WORD $0x38656945 // ldrb	w5, [x10, x5]
	WORD $0x394009a6 // ldrb	w6, [x13, #2]
	WORD $0x38666946 // ldrb	w6, [x10, x6]
	WORD $0x39400db3 // ldrb	w19, [x13, #3]
	WORD $0x38736953 // ldrb	w19, [x10, x19]
	WORD $0x394011b4 // ldrb	w20, [x13, #4]
	WORD $0x38746954 // ldrb	w20, [x10, x20]
	WORD $0x394015b5 // ldrb	w21, [x13, #5]
	WORD $0x38756955 // ldrb	w21, [x10, x21]
	WORD $0x394019b6 // ldrb	w22, [x13, #6]
	WORD $0x38766956 // ldrb	w22, [x10, x22]
	WORD $0x39401db7 // ldrb	w23, [x13, #7]
	WORD $0x38776957 // ldrb	w23, [x10, x23]
	WORD $0x2a0400b8 // orr	w24, w5, w4
	WORD $0x2a060318 // orr	w24, w24, w6
	WORD $0x2a130318 // orr	w24, w24, w19
	WORD $0x2a140318 // orr	w24, w24, w20
	WORD $0x2a150318 // orr	w24, w24, w21
	WORD $0x2a160318 // orr	w24, w24, w22
	WORD $0x2a170318 // orr	w24, w24, w23
	WORD $0x2a3803f8 // mvn	w24, w24
	WORD $0x72001f1f // tst	w24, #0xff
	WORD $0x54000401 // b.ne	736 // LBB1_13
	WORD $0xeb0901bf // cmp	x13, x9
	WORD $0x54000582 // b.hs	792 // LBB1_14
	WORD $0x52800005 // mov	w5, #0
	WORD $0x52800004 // mov	w4, #0
	WORD $0x910005a6 // add	x6, x13, #1
	WORD $0x12001cf3 // and	w19, w7, #0xff
	WORD $0x71002a7f // cmp	w19, #10
	WORD $0x7a4d1a64 // ccmp	w19, #13, #4, ne
	WORD $0x54000200 // b.eq	708 // LBB1_10
	WORD $0x14000006 // b	672 // LBB1_8

	// LBB1_7:
	WORD $0x384014c7 // ldrb	w7, [x6], #1
	WORD $0x12001cf3 // and	w19, w7, #0xff
	WORD $0x71002a7f // cmp	w19, #10
	WORD $0x7a4d1a64 // ccmp	w19, #13, #4, ne
	WORD $0x54000140 // b.eq	708 // LBB1_10

	// LBB1_8:
	WORD $0x92401ce7 // and	x7, x7, #0xff
	WORD $0x38676947 // ldrb	w7, [x10, x7]
	WORD $0x7103fcff // cmp	w7, #255
	WORD $0x54000580 // b.eq	860 // LBB1_19
	WORD $0x110004a5 // add	w5, w5, #1
	WORD $0x2a0418e4 // orr	w4, w7, w4, lsl #6
	WORD $0x71000cbf // cmp	w5, #3
	WORD $0x5400008d // b.le	716 // LBB1_11
	WORD $0x14000005 // b	724 // LBB1_12

	// LBB1_10:
	WORD $0x71000cbf // cmp	w5, #3
	WORD $0x5400006c // b.gt	724 // LBB1_12

	// LBB1_11:
	WORD $0xeb0900df // cmp	x6, x9
	WORD $0x54fffde3 // b.lo	652 // LBB1_7

	// LBB1_12:
	WORD $0x710004bf // cmp	w5, #1
	WORD $0x54000581 // b.ne	904 // LBB1_23
	WORD $0x14000023 // b	872 // LBB1_20

	// LBB1_13:
	WORD $0xd34c2ca5 // lsl	x5, x5, #52
	WORD $0xaa04e8a4 // orr	x4, x5, x4, lsl #58
	WORD $0xaa06b884 // orr	x4, x4, x6, lsl #46
	WORD $0xaa13a084 // orr	x4, x4, x19, lsl #40
	WORD $0xaa148884 // orr	x4, x4, x20, lsl #34
	WORD $0xaa157084 // orr	x4, x4, x21, lsl #28
	WORD $0xaa165884 // orr	x4, x4, x22, lsl #22
	WORD $0xaa174084 // orr	x4, x4, x23, lsl #16
	WORD $0xdac00c84 // rev	x4, x4
	WORD $0xf8006584 // str	x4, [x12], #6
	WORD $0x910021ad // add	x13, x13, #8
	WORD $0xeb1001bf // cmp	x13, x16
	WORD $0x54000369 // b.ls	892 // LBB1_22
	WORD $0x1400005d // b	1160 // LBB1_44

	// LBB1_14:
	WORD $0x52800005 // mov	w5, #0
	WORD $0x52800004 // mov	w4, #0
	WORD $0xaa0d03e6 // mov	x6, x13
	WORD $0x54000540 // b.eq	972 // LBB1_30

	// LBB1_15:
	WORD $0xeb0b00df // cmp	x6, x11
	WORD $0x540001e2 // b.hs	872 // LBB1_20
	WORD $0xaa0603e7 // mov	x7, x6
	WORD $0x384014f3 // ldrb	w19, [x7], #1
	WORD $0x7100f67f // cmp	w19, #61
	WORD $0x540000a1 // b.ne	848 // LBB1_18
	WORD $0x910008c7 // add	x7, x6, #2
	WORD $0x394004c6 // ldrb	w6, [x6, #1]
	WORD $0x7100f4df // cmp	w6, #61
	WORD $0x54000340 // b.eq	948 // LBB1_28

	// LBB1_18:
	WORD $0xcb0d00e4 // sub	x4, x7, x13
	WORD $0xb4000104 // cbz	x4, 884 // LBB1_21
	WORD $0x1400003d // b	1100 // LBB1_41

	// LBB1_19:
	WORD $0xd10004c6 // sub	x6, x6, #1
	WORD $0x710004bf // cmp	w5, #1
	WORD $0x54000121 // b.ne	904 // LBB1_23

	// LBB1_20:
	WORD $0xcb0d00c4 // sub	x4, x6, x13
	WORD $0x91000484 // add	x4, x4, #1
	WORD $0xb50006e4 // cbnz	x4, 1100 // LBB1_41

	// LBB1_21:
	WORD $0xeb1001bf // cmp	x13, x16
	WORD $0x54000888 // b.hi	1160 // LBB1_44

	// LBB1_22:
	WORD $0xeb11019f // cmp	x12, x17
	WORD $0x54fff3e9 // b.ls	508 // LBB1_4
	WORD $0x14000041 // b	1160 // LBB1_44

	// LBB1_23:
	WORD $0x71000cbf // cmp	w5, #3
	WORD $0x540003ac // b.gt	1024 // LBB1_33
	WORD $0xeb0900df // cmp	x6, x9
	WORD $0x540001c0 // b.eq	972 // LBB1_30
	WORD $0x71000cbf // cmp	w5, #3
	WORD $0x54fffc61 // b.ne	808 // LBB1_15
	WORD $0x384014c5 // ldrb	w5, [x6], #1
	WORD $0x7100f4bf // cmp	w5, #61
	WORD $0x540004e1 // b.ne	1092 // LBB1_40
	WORD $0x52800065 // mov	w5, #3
	WORD $0xaa0603e7 // mov	x7, x6

	// LBB1_28:
	WORD $0xeb0900ff // cmp	x7, x9
	WORD $0x54000142 // b.hs	992 // LBB1_32
	WORD $0xcb0d00e4 // sub	x4, x7, x13
	WORD $0x91000484 // add	x4, x4, #1
	WORD $0xb4fffd84 // cbz	x4, 884 // LBB1_21
	WORD $0x14000021 // b	1100 // LBB1_41

	// LBB1_30:
	WORD $0xaa0903e7 // mov	x7, x9
	WORD $0x37080083 // tbnz	w3, #1, 992 // LBB1_32
	WORD $0xcb0d01c4 // sub	x4, x14, x13
	WORD $0xb4fffce4 // cbz	x4, 884 // LBB1_21
	WORD $0x1400001c // b	1100 // LBB1_41

	// LBB1_32:
	WORD $0x4b05004d // sub	w13, w2, w5
	WORD $0xb0d05ad  // add	w13, w13, w13, lsl #1
	WORD $0x531f79ad // lsl	w13, w13, #1
	WORD $0x1acd2084 // lsl	w4, w4, w13
	WORD $0xaa0703ed // mov	x13, x7
	WORD $0x710008bf // cmp	w5, #2
	WORD $0x540000a1 // b.ne	1036 // LBB1_34
	WORD $0x1400000b // b	1064 // LBB1_38

	// LBB1_33:
	WORD $0xaa0603ed // mov	x13, x6
	WORD $0x710008bf // cmp	w5, #2
	WORD $0x54000100 // b.eq	1064 // LBB1_38

	// LBB1_34:
	WORD $0x71000cbf // cmp	w5, #3
	WORD $0x54000080 // b.eq	1056 // LBB1_37
	WORD $0x710010bf // cmp	w5, #4
	WORD $0x540000c1 // b.ne	1072 // LBB1_39
	WORD $0x39000984 // strb	w4, [x12, #2]

	// LBB1_37:
	WORD $0x53087c86 // lsr	w6, w4, #8
	WORD $0x39000586 // strb	w6, [x12, #1]

	// LBB1_38:
	WORD $0x53107c84 // lsr	w4, w4, #16
	WORD $0x39000184 // strb	w4, [x12]

	// LBB1_39:
	WORD $0x8b25c18c // add	x12, x12, w5, sxtw
	WORD $0xd100058c // sub	x12, x12, #1
	WORD $0xeb1001bf // cmp	x13, x16
	WORD $0x54fffa09 // b.ls	892 // LBB1_22
	WORD $0x14000012 // b	1160 // LBB1_44

	// LBB1_40:
	WORD $0xcb0d00c4 // sub	x4, x6, x13
	WORD $0xb4fff964 // cbz	x4, 884 // LBB1_21

	// LBB1_41:
	WORD $0x8b0d0088 // add	x8, x4, x13
	WORD $0xcb080028 // sub	x8, x1, x8
	WORD $0xaa0803e0 // mov	x0, x8
	WORD $0xa9424ff4 // ldp	x20, x19, [sp, #32]
	WORD $0xa94157f6 // ldp	x22, x21, [sp, #16]
	WORD $0xa8c35ff8 // ldp	x24, x23, [sp], #48
	WORD $0xd65f03c0 // ret

	// LBB1_42:
	WORD $0xd2800008 // mov	x8, #0
	WORD $0xaa0803e0 // mov	x0, x8
	WORD $0xa9424ff4 // ldp	x20, x19, [sp, #32]
	WORD $0xa94157f6 // ldp	x22, x21, [sp, #16]
	WORD $0xa8c35ff8 // ldp	x24, x23, [sp], #48
	WORD $0xd65f03c0 // ret

	// LBB1_43:
	WORD $0xaa0803ec // mov	x12, x8
	WORD $0xaa0103ed // mov	x13, x1

	// LBB1_44:
	WORD $0xd1001130 // sub	x16, x9, #4
	WORD $0xeb1001bf // cmp	x13, x16
	WORD $0x540011e8 // b.hi	1740 // LBB1_85
	WORD $0xd10011ef // sub	x15, x15, #4
	WORD $0xeb0f019f // cmp	x12, x15
	WORD $0x54001188 // b.hi	1740 // LBB1_85
	WORD $0x52800091 // mov	w17, #4

	// LBB1_47:
	WORD $0x394001a6 // ldrb	w6, [x13]
	WORD $0x38666942 // ldrb	w2, [x10, x6]
	WORD $0x394005a4 // ldrb	w4, [x13, #1]
	WORD $0x38646944 // ldrb	w4, [x10, x4]
	WORD $0x394009a5 // ldrb	w5, [x13, #2]
	WORD $0x38656945 // ldrb	w5, [x10, x5]
	WORD $0x39400da7 // ldrb	w7, [x13, #3]
	WORD $0x38676947 // ldrb	w7, [x10, x7]
	WORD $0x2a020093 // orr	w19, w4, w2
	WORD $0x2a050273 // orr	w19, w19, w5
	WORD $0x2a070273 // orr	w19, w19, w7
	WORD $0x7103fe7f // cmp	w19, #255
	WORD $0x54000401 // b.ne	1364 // LBB1_56
	WORD $0xeb0901bf // cmp	x13, x9
	WORD $0x54000502 // b.hs	1404 // LBB1_57
	WORD $0x52800004 // mov	w4, #0
	WORD $0x52800002 // mov	w2, #0
	WORD $0x910005a5 // add	x5, x13, #1
	WORD $0x12001cc7 // and	w7, w6, #0xff
	WORD $0x710028ff // cmp	w7, #10
	WORD $0x7a4d18e4 // ccmp	w7, #13, #4, ne
	WORD $0x54000200 // b.eq	1336 // LBB1_53
	WORD $0x14000006 // b	1300 // LBB1_51

	// LBB1_50:
	WORD $0x384014a6 // ldrb	w6, [x5], #1
	WORD $0x12001cc7 // and	w7, w6, #0xff
	WORD $0x710028ff // cmp	w7, #10
	WORD $0x7a4d18e4 // ccmp	w7, #13, #4, ne
	WORD $0x54000140 // b.eq	1336 // LBB1_53

	// LBB1_51:
	WORD $0x92401cc6 // and	x6, x6, #0xff
	WORD $0x38666946 // ldrb	w6, [x10, x6]
	WORD $0x7103fcdf // cmp	w6, #255
	WORD $0x54000500 // b.eq	1472 // LBB1_62
	WORD $0x11000484 // add	w4, w4, #1
	WORD $0x2a0218c2 // orr	w2, w6, w2, lsl #6
	WORD $0x71000c9f // cmp	w4, #3
	WORD $0x5400008d // b.le	1344 // LBB1_54
	WORD $0x14000005 // b	1352 // LBB1_55

	// LBB1_53:
	WORD $0x71000c9f // cmp	w4, #3
	WORD $0x5400006c // b.gt	1352 // LBB1_55

	// LBB1_54:
	WORD $0xeb0900bf // cmp	x5, x9
	WORD $0x54fffde3 // b.lo	1280 // LBB1_50

	// LBB1_55:
	WORD $0x7100049f // cmp	w4, #1
	WORD $0x54000501 // b.ne	1516 // LBB1_66
	WORD $0x1400001f // b	1484 // LBB1_63

	// LBB1_56:
	WORD $0x530c2c84 // lsl	w4, w4, #20
	WORD $0x2a026882 // orr	w2, w4, w2, lsl #26
	WORD $0x2a053842 // orr	w2, w2, w5, lsl #14
	WORD $0x2a072042 // orr	w2, w2, w7, lsl #8
	WORD $0x5ac00842 // rev	w2, w2
	WORD $0xb8003582 // str	w2, [x12], #3
	WORD $0x910011ad // add	x13, x13, #4
	WORD $0xeb1001bf // cmp	x13, x16
	WORD $0x54000369 // b.ls	1504 // LBB1_65
	WORD $0x14000055 // b	1740 // LBB1_85

	// LBB1_57:
	WORD $0x52800004 // mov	w4, #0
	WORD $0x52800002 // mov	w2, #0
	WORD $0xaa0d03e5 // mov	x5, x13
	WORD $0x54000540 // b.eq	1584 // LBB1_73

	// LBB1_58:
	WORD $0xeb0b00bf // cmp	x5, x11
	WORD $0x540001e2 // b.hs	1484 // LBB1_63
	WORD $0xaa0503e6 // mov	x6, x5
	WORD $0x384014c7 // ldrb	w7, [x6], #1
	WORD $0x7100f4ff // cmp	w7, #61
	WORD $0x540000a1 // b.ne	1460 // LBB1_61
	WORD $0x910008a6 // add	x6, x5, #2
	WORD $0x394004a5 // ldrb	w5, [x5, #1]
	WORD $0x7100f4bf // cmp	w5, #61
	WORD $0x54000340 // b.eq	1560 // LBB1_71

	// LBB1_61:
	WORD $0xcb0d00c2 // sub	x2, x6, x13
	WORD $0xb4000102 // cbz	x2, 1496 // LBB1_64
	WORD $0x1400003d // b	1712 // LBB1_84

	// LBB1_62:
	WORD $0xd10004a5 // sub	x5, x5, #1
	WORD $0x7100049f // cmp	w4, #1
	WORD $0x54000121 // b.ne	1516 // LBB1_66

	// LBB1_63:
	WORD $0xcb0d00a2 // sub	x2, x5, x13
	WORD $0x91000442 // add	x2, x2, #1
	WORD $0xb50006e2 // cbnz	x2, 1712 // LBB1_84

	// LBB1_64:
	WORD $0xeb1001bf // cmp	x13, x16
	WORD $0x54000788 // b.hi	1740 // LBB1_85

	// LBB1_65:
	WORD $0xeb0f019f // cmp	x12, x15
	WORD $0x54fff609 // b.ls	1188 // LBB1_47
	WORD $0x14000039 // b	1740 // LBB1_85

	// LBB1_66:
	WORD $0x71000c9f // cmp	w4, #3
	WORD $0x540003ac // b.gt	1636 // LBB1_76
	WORD $0xeb0900bf // cmp	x5, x9
	WORD $0x540001c0 // b.eq	1584 // LBB1_73
	WORD $0x71000c9f // cmp	w4, #3
	WORD $0x54fffc61 // b.ne	1420 // LBB1_58
	WORD $0x384014a4 // ldrb	w4, [x5], #1
	WORD $0x7100f49f // cmp	w4, #61
	WORD $0x540004e1 // b.ne	1704 // LBB1_83
	WORD $0x52800064 // mov	w4, #3
	WORD $0xaa0503e6 // mov	x6, x5

	// LBB1_71:
	WORD $0xeb0900df // cmp	x6, x9
	WORD $0x54000142 // b.hs	1604 // LBB1_75
	WORD $0xcb0d00c2 // sub	x2, x6, x13
	WORD $0x91000442 // add	x2, x2, #1
	WORD $0xb4fffd82 // cbz	x2, 1496 // LBB1_64
	WORD $0x14000021 // b	1712 // LBB1_84

	// LBB1_73:
	WORD $0xaa0903e6 // mov	x6, x9
	WORD $0x37080083 // tbnz	w3, #1, 1604 // LBB1_75
	WORD $0xcb0d01c2 // sub	x2, x14, x13
	WORD $0xb4fffce2 // cbz	x2, 1496 // LBB1_64
	WORD $0x1400001c // b	1712 // LBB1_84

	// LBB1_75:
	WORD $0x4b04022d // sub	w13, w17, w4
	WORD $0xb0d05ad  // add	w13, w13, w13, lsl #1
	WORD $0x531f79ad // lsl	w13, w13, #1
	WORD $0x1acd2042 // lsl	w2, w2, w13
	WORD $0xaa0603ed // mov	x13, x6
	WORD $0x7100089f // cmp	w4, #2
	WORD $0x540000a1 // b.ne	1648 // LBB1_77
	WORD $0x1400000b // b	1676 // LBB1_81

	// LBB1_76:
	WORD $0xaa0503ed // mov	x13, x5
	WORD $0x7100089f // cmp	w4, #2
	WORD $0x54000100 // b.eq	1676 // LBB1_81

	// LBB1_77:
	WORD $0x71000c9f // cmp	w4, #3
	WORD $0x54000080 // b.eq	1668 // LBB1_80
	WORD $0x7100109f // cmp	w4, #4
	WORD $0x540000c1 // b.ne	1684 // LBB1_82
	WORD $0x39000982 // strb	w2, [x12, #2]

	// LBB1_80:
	WORD $0x53087c45 // lsr	w5, w2, #8
	WORD $0x39000585 // strb	w5, [x12, #1]

	// LBB1_81:
	WORD $0x53107c42 // lsr	w2, w2, #16
	WORD $0x39000182 // strb	w2, [x12]

	// LBB1_82:
	WORD $0x8b24c18c // add	x12, x12, w4, sxtw
	WORD $0xd100058c // sub	x12, x12, #1
	WORD $0xeb1001bf // cmp	x13, x16
	WORD $0x54fffa09 // b.ls	1504 // LBB1_65
	WORD $0x1400000a // b	1740 // LBB1_85

	// LBB1_83:
	WORD $0xcb0d00a2 // sub	x2, x5, x13
	WORD $0xb4fff962 // cbz	x2, 1496 // LBB1_64

	// LBB1_84:
	WORD $0x8b0d0048 // add	x8, x2, x13
	WORD $0xcb080028 // sub	x8, x1, x8
	WORD $0xaa0803e0 // mov	x0, x8
	WORD $0xa9424ff4 // ldp	x20, x19, [sp, #32]
	WORD $0xa94157f6 // ldp	x22, x21, [sp, #16]
	WORD $0xa8c35ff8 // ldp	x24, x23, [sp], #48
	WORD $0xd65f03c0 // ret

	// LBB1_85:
	WORD $0x37080b43 // tbnz	w3, #1, 2100 // LBB1_116
	WORD $0x5280008f // mov	w15, #4
	WORD $0x14000004 // b	1764 // LBB1_88

	// LBB1_87:
	WORD $0xcb0d0050 // sub	x16, x2, x13
	WORD $0x91000610 // add	x16, x16, #1
	WORD $0xb5001670 // cbnz	x16, 2476 // LBB1_149

	// LBB1_88:
	WORD $0xeb0901bf // cmp	x13, x9
	WORD $0x540014e2 // b.hs	2436 // LBB1_147
	WORD $0x52800010 // mov	w16, #0
	WORD $0x52800011 // mov	w17, #0
	WORD $0xaa0d03e2 // mov	x2, x13

	// LBB1_90:
	WORD $0x39400043 // ldrb	w3, [x2]
	WORD $0x7100287f // cmp	w3, #10
	WORD $0x7a4d1864 // ccmp	w3, #13, #4, ne
	WORD $0x540000a1 // b.ne	1816 // LBB1_92
	WORD $0x91000442 // add	x2, x2, #1
	WORD $0x71000e1f // cmp	w16, #3
	WORD $0x5400014d // b.le	1848 // LBB1_94
	WORD $0x1400000b // b	1856 // LBB1_95

	// LBB1_92:
	WORD $0x38636943 // ldrb	w3, [x10, x3]
	WORD $0x7103fc7f // cmp	w3, #255
	WORD $0x54000100 // b.eq	1856 // LBB1_95
	WORD $0x11000610 // add	w16, w16, #1
	WORD $0x2a111871 // orr	w17, w3, w17, lsl #6
	WORD $0x91000442 // add	x2, x2, #1
	WORD $0x71000e1f // cmp	w16, #3
	WORD $0x5400006c // b.gt	1856 // LBB1_95

	// LBB1_94:
	WORD $0xeb09005f // cmp	x2, x9
	WORD $0x54fffde3 // b.lo	1784 // LBB1_90

	// LBB1_95:
	WORD $0x7100061f // cmp	w16, #1
	WORD $0x54fffca0 // b.eq	1752 // LBB1_87
	WORD $0x71000e1f // cmp	w16, #3
	WORD $0x5400018c // b.gt	1916 // LBB1_101
	WORD $0xeb09005f // cmp	x2, x9
	WORD $0x54000340 // b.eq	1980 // LBB1_108
	WORD $0x71000e1f // cmp	w16, #3
	WORD $0x54000361 // b.ne	1992 // LBB1_109
	WORD $0x38401444 // ldrb	w4, [x2], #1
	WORD $0xaa0203e3 // mov	x3, x2
	WORD $0x7100f49f // cmp	w4, #61
	WORD $0x54000420 // b.eq	2032 // LBB1_112
	WORD $0xcb0d0050 // sub	x16, x2, x13
	WORD $0xb4fffb90 // cbz	x16, 1764 // LBB1_88
	WORD $0x1400008d // b	2476 // LBB1_149

	// LBB1_101:
	WORD $0xaa0203ed // mov	x13, x2
	WORD $0x71000a1f // cmp	w16, #2
	WORD $0x54000100 // b.eq	1956 // LBB1_106

	// LBB1_102:
	WORD $0x71000e1f // cmp	w16, #3
	WORD $0x54000080 // b.eq	1948 // LBB1_105
	WORD $0x7100121f // cmp	w16, #4
	WORD $0x540000c1 // b.ne	1964 // LBB1_107
	WORD $0x39000991 // strb	w17, [x12, #2]

	// LBB1_105:
	WORD $0x53087e22 // lsr	w2, w17, #8
	WORD $0x39000582 // strb	w2, [x12, #1]

	// LBB1_106:
	WORD $0x53107e31 // lsr	w17, w17, #16
	WORD $0x39000191 // strb	w17, [x12]

	// LBB1_107:
	WORD $0x8b30c18c // add	x12, x12, w16, sxtw
	WORD $0xd100058c // sub	x12, x12, #1
	WORD $0xb4fff99f // cbz	xzr, 1764 // LBB1_88
	WORD $0x1400007c // b	2472 // LBB1_148

	// LBB1_108:
	WORD $0xcb0d01d0 // sub	x16, x14, x13
	WORD $0xb4fff930 // cbz	x16, 1764 // LBB1_88
	WORD $0x1400007a // b	2476 // LBB1_149

	// LBB1_109:
	WORD $0xeb0b005f // cmp	x2, x11
	WORD $0x54fff862 // b.hs	1752 // LBB1_87
	WORD $0xaa0203e3 // mov	x3, x2
	WORD $0x38401464 // ldrb	w4, [x3], #1
	WORD $0x7100f49f // cmp	w4, #61
	WORD $0x54000161 // b.ne	2056 // LBB1_114
	WORD $0x91000843 // add	x3, x2, #2
	WORD $0x39400442 // ldrb	w2, [x2, #1]
	WORD $0x7100f45f // cmp	w2, #61
	WORD $0x540000e1 // b.ne	2056 // LBB1_114

	// LBB1_112:
	WORD $0xeb09007f // cmp	x3, x9
	WORD $0x54000102 // b.hs	2068 // LBB1_115
	WORD $0xcb0d0070 // sub	x16, x3, x13
	WORD $0x91000610 // add	x16, x16, #1
	WORD $0xb4fff730 // cbz	x16, 1764 // LBB1_88
	WORD $0x1400006a // b	2476 // LBB1_149

	// LBB1_114:
	WORD $0xcb0d0070 // sub	x16, x3, x13
	WORD $0xb4fff6d0 // cbz	x16, 1764 // LBB1_88
	WORD $0x14000067 // b	2476 // LBB1_149

	// LBB1_115:
	WORD $0x4b1001ed // sub	w13, w15, w16
	WORD $0xb0d05ad  // add	w13, w13, w13, lsl #1
	WORD $0x531f79ad // lsl	w13, w13, #1
	WORD $0x1acd2231 // lsl	w17, w17, w13
	WORD $0xaa0303ed // mov	x13, x3
	WORD $0x71000a1f // cmp	w16, #2
	WORD $0x54fffae1 // b.ne	1928 // LBB1_102
	WORD $0x17ffffdd // b	1956 // LBB1_106

	// LBB1_116:
	WORD $0x5280008e // mov	w14, #4
	WORD $0x14000009 // b	2140 // LBB1_121

	// LBB1_117:
	WORD $0x53087e11 // lsr	w17, w16, #8
	WORD $0x39000591 // strb	w17, [x12, #1]

	// LBB1_118:
	WORD $0x53107e10 // lsr	w16, w16, #16
	WORD $0x39000190 // strb	w16, [x12]

	// LBB1_119:
	WORD $0xd2800010 // mov	x16, #0
	WORD $0x8b2fc18c // add	x12, x12, w15, sxtw
	WORD $0xd100058c // sub	x12, x12, #1

	// LBB1_120:
	WORD $0xb5000ab0 // cbnz	x16, 2476 // LBB1_149

	// LBB1_121:
	WORD $0xeb0901bf // cmp	x13, x9
	WORD $0x54000922 // b.hs	2436 // LBB1_147
	WORD $0x5280000f // mov	w15, #0
	WORD $0x52800010 // mov	w16, #0
	WORD $0xaa0d03f1 // mov	x17, x13

	// LBB1_123:
	WORD $0x39400222 // ldrb	w2, [x17]
	WORD $0x7100285f // cmp	w2, #10
	WORD $0x7a4d1844 // ccmp	w2, #13, #4, ne
	WORD $0x540000a1 // b.ne	2192 // LBB1_125
	WORD $0x91000631 // add	x17, x17, #1
	WORD $0x71000dff // cmp	w15, #3
	WORD $0x5400014d // b.le	2224 // LBB1_127
	WORD $0x1400000b // b	2232 // LBB1_128

	// LBB1_125:
	WORD $0x38626942 // ldrb	w2, [x10, x2]
	WORD $0x7103fc5f // cmp	w2, #255
	WORD $0x54000100 // b.eq	2232 // LBB1_128
	WORD $0x110005ef // add	w15, w15, #1
	WORD $0x2a101850 // orr	w16, w2, w16, lsl #6
	WORD $0x91000631 // add	x17, x17, #1
	WORD $0x71000dff // cmp	w15, #3
	WORD $0x5400006c // b.gt	2232 // LBB1_128

	// LBB1_127:
	WORD $0xeb09023f // cmp	x17, x9
	WORD $0x54fffde3 // b.lo	2160 // LBB1_123

	// LBB1_128:
	WORD $0x710005ff // cmp	w15, #1
	WORD $0x54000081 // b.ne	2252 // LBB1_131

	// LBB1_129:
	WORD $0xcb0d022f // sub	x15, x17, x13

	// LBB1_130:
	WORD $0x910005f0 // add	x16, x15, #1
	WORD $0x17ffffe4 // b	2136 // LBB1_120

	// LBB1_131:
	WORD $0x71000dff // cmp	w15, #3
	WORD $0x5400018c // b.gt	2304 // LBB1_136
	WORD $0xaa0903e2 // mov	x2, x9
	WORD $0xeb09023f // cmp	x17, x9
	WORD $0x54000360 // b.eq	2376 // LBB1_142
	WORD $0x71000dff // cmp	w15, #3
	WORD $0x54000161 // b.ne	2320 // LBB1_137
	WORD $0x38401623 // ldrb	w3, [x17], #1
	WORD $0xaa1103e2 // mov	x2, x17
	WORD $0x7100f47f // cmp	w3, #61
	WORD $0x54000220 // b.eq	2360 // LBB1_140
	WORD $0xcb0d0230 // sub	x16, x17, x13
	WORD $0x17ffffd7 // b	2136 // LBB1_120

	// LBB1_136:
	WORD $0xaa1103ed // mov	x13, x17
	WORD $0x710009ff // cmp	w15, #2
	WORD $0x540002e1 // b.ne	2404 // LBB1_143
	WORD $0x17ffffce // b	2116 // LBB1_118

	// LBB1_137:
	WORD $0xeb0b023f // cmp	x17, x11
	WORD $0x54fffd62 // b.hs	2240 // LBB1_129
	WORD $0xaa1103e2 // mov	x2, x17
	WORD $0x38401443 // ldrb	w3, [x2], #1
	WORD $0x7100f47f // cmp	w3, #61
	WORD $0x540002c1 // b.ne	2428 // LBB1_146
	WORD $0x91000a22 // add	x2, x17, #2
	WORD $0x39400631 // ldrb	w17, [x17, #1]
	WORD $0x7100f63f // cmp	w17, #61
	WORD $0x54000241 // b.ne	2428 // LBB1_146

	// LBB1_140:
	WORD $0xeb09005f // cmp	x2, x9
	WORD $0x54000062 // b.hs	2376 // LBB1_142
	WORD $0xcb0d004f // sub	x15, x2, x13
	WORD $0x17ffffe0 // b	2244 // LBB1_130

	// LBB1_142:
	WORD $0x4b0f01cd // sub	w13, w14, w15
	WORD $0xb0d05ad  // add	w13, w13, w13, lsl #1
	WORD $0x531f79ad // lsl	w13, w13, #1
	WORD $0x1acd2210 // lsl	w16, w16, w13
	WORD $0xaa0203ed // mov	x13, x2
	WORD $0x710009ff // cmp	w15, #2
	WORD $0x54fff720 // b.eq	2116 // LBB1_118

	// LBB1_143:
	WORD $0x71000dff // cmp	w15, #3
	WORD $0x54fff6a0 // b.eq	2108 // LBB1_117
	WORD $0x710011ff // cmp	w15, #4
	WORD $0x54fff6e1 // b.ne	2124 // LBB1_119
	WORD $0x39000990 // strb	w16, [x12, #2]
	WORD $0x17ffffb1 // b	2108 // LBB1_117

	// LBB1_146:
	WORD $0xcb0d0050 // sub	x16, x2, x13
	WORD $0x17ffffb6 // b	2136 // LBB1_120

	// LBB1_147:
	WORD $0xf9400409 // ldr	x9, [x0, #8]
	WORD $0xcb080188 // sub	x8, x12, x8
	WORD $0x8b080129 // add	x9, x9, x8
	WORD $0xf9000409 // str	x9, [x0, #8]
	WORD $0xaa0803e0 // mov	x0, x8
	WORD $0xa9424ff4 // ldp	x20, x19, [sp, #32]
	WORD $0xa94157f6 // ldp	x22, x21, [sp, #16]
	WORD $0xa8c35ff8 // ldp	x24, x23, [sp], #48
	WORD $0xd65f03c0 // ret

	// LBB1_148:
	WORD $0xd2800010 // mov	x16, #0

	// LBB1_149:
	WORD $0x8b0d0208 // add	x8, x16, x13
	WORD $0xcb080028 // sub	x8, x1, x8
	WORD $0xaa0803e0 // mov	x0, x8
	WORD $0xa9424ff4 // ldp	x20, x19, [sp, #32]
	WORD $0xa94157f6 // ldp	x22, x21, [sp, #16]
	WORD $0xa8c35ff8 // ldp	x24, x23, [sp], #48
	WORD $0xd65f03c0 // ret

	// _TabEncodeCharsetStd:
	DWORD $0x4847464544434241
	DWORD $0x504f4e4d4c4b4a49
	DWORD $0x5857565554535251
	DWORD $0x6665646362615a59
	DWORD $0x6e6d6c6b6a696867
	DWORD $0x767574737271706f
	DWORD $0x333231307a797877
	DWORD $0x2f2b393837363534

	// _TabEncodeCharsetURL:
	DWORD $0x4847464544434241
	DWORD $0x504f4e4d4c4b4a49
	DWORD $0x5857565554535251
	DWORD $0x6665646362615a59
	DWORD $0x6e6d6c6b6a696867
	DWORD $0x767574737271706f
	DWORD $0x333231307a797877
	DWORD $0x5f2d393837363534

	// _VecDecodeCharsetStd:
	DWORD $0xffffffffffffffff
	DWORD $0xffffffffffffffff
	DWORD $0xffffffffffffffff
	DWORD $0xffffffffffffffff
	DWORD $0xffffffffffffffff
	DWORD $0x3fffffff3effffff
	DWORD $0x3b3a393837363534
	DWORD $0xffffffffffff3d3c
	DWORD $0x6050403020100ff
	DWORD $0xe0d0c0b0a090807
	DWORD $0x161514131211100f
	DWORD $0xffffffffff191817
	DWORD $0x201f1e1d1c1b1aff
	DWORD $0x2827262524232221
	DWORD $0x302f2e2d2c2b2a29
	DWORD $0xffffffffff333231
	DWORD $0xffffffffffffffff
	DWORD $0xffffffffffffffff
	DWORD $0xffffffffffffffff
	DWORD $0xffffffffffffffff
	DWORD $0xffffffffffffffff
	DWORD $0xffffffffffffffff
	DWORD $0xffffffffffffffff
	DWORD $0xffffffffffffffff
	DWORD $0xffffffffffffffff
	DWORD $0xffffffffffffffff
	DWORD $0xffffffffffffffff
	DWORD $0xffffffffffffffff
	DWORD $0xffffffffffffffff
	DWORD $0xffffffffffffffff
	DWORD $0xffffffffffffffff
	DWORD $0xffffffffffffffff

	// _VecDecodeCharsetURL:
	DWORD $0xffffffffffffffff
	DWORD $0xffffffffffffffff
	DWORD $0xffffffffffffffff
	DWORD $0xffffffffffffffff
	DWORD $0xffffffffffffffff
	DWORD $0xffff3effffffffff
	DWORD $0x3b3a393837363534
	DWORD $0xffffffffffff3d3c
	DWORD $0x6050403020100ff
	DWORD $0xe0d0c0b0a090807
	DWORD $0x161514131211100f
	DWORD $0x3fffffffff191817
	DWORD $0x201f1e1d1c1b1aff
	DWORD $0x2827262524232221
	DWORD $0x302f2e2d2c2b2a29
	DWORD $0xffffffffff333231
	DWORD $0xffffffffffffffff
	DWORD $0xffffffffffffffff
	DWORD $0xffffffffffffffff
	DWORD $0xffffffffffffffff
	DWORD $0xffffffffffffffff
	DWORD $0xffffffffffffffff
	DWORD $0xffffffffffffffff
	DWORD $0xffffffffffffffff
	DWORD $0xffffffffffffffff
	DWORD $0xffffffffffffffff
	DWORD $0xffffffffffffffff
	DWORD $0xffffffffffffffff
	DWORD $0xffffffffffffffff
	DWORD $0xffffffffffffffff
	DWORD $0xffffffffffffffff
	DWORD $0xffffffffffffffff

	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP
	NOOP

	WORD $0x10000000 // adr	x0, 0
	WORD $0xf90007e0 // str	x0, [sp, #8]
	WORD $0xd65f03c0 // ret

	// _b64encode:
	WORD $0xf9400429 // ldr	x9, [x1, #8]
	WORD $0xb4000c09 // cbz	x9, 400 // LBB0_17
	WORD $0xa9402808 // ldp	x8, x10, [x0]
	WORD $0x8b0a0108 // add	x8, x8, x10
	WORD $0xf940002b // ldr	x11, [x1]
	WORD $0x8b09016c // add	x12, x11, x9
	WORD $0x90000009 // adrp	x9, 0 // _TabEncodeCharsetURL
	WORD $0x91282129 // add	x9, x9, 2568 // _TabEncodeCharsetURL
	WORD $0x9000000a // adrp	x10, 0 // _TabEncodeCharsetStd
	WORD $0x9127214a // add	x10, x10, 2504 // _TabEncodeCharsetStd
	WORD $0x7200005f // tst	w2, #0x1
	WORD $0x9a89014a // csel	x10, x10, x9, eq
	WORD $0xd100118d // sub	x13, x12, #4
	WORD $0xeb0d017f // cmp	x11, x13
	WORD $0x54000069 // b.ls	80 // LBB0_3
	WORD $0xaa0803e9 // mov	x9, x8
	WORD $0x14000014 // b	156 // LBB0_5

	// LBB0_3:
	WORD $0xaa0803ee // mov	x14, x8

	// LBB0_4:
	WORD $0xb8403569 // ldr	w9, [x11], #3
	WORD $0x5ac00929 // rev	w9, w9
	WORD $0xd35afd2f // lsr	x15, x9, #26
	WORD $0xd3546530 // ubfx	x16, x9, #20, #6
	WORD $0xd34e4d31 // ubfx	x17, x9, #14, #6
	WORD $0xd3483529 // ubfx	x9, x9, #8, #6
	WORD $0x386f694f // ldrb	w15, [x10, x15]
	WORD $0x390001cf // strb	w15, [x14]
	WORD $0x3870694f // ldrb	w15, [x10, x16]
	WORD $0x390005cf // strb	w15, [x14, #1]
	WORD $0x3871694f // ldrb	w15, [x10, x17]
	WORD $0x390009cf // strb	w15, [x14, #2]
	WORD $0x3869694f // ldrb	w15, [x10, x9]
	WORD $0x910011c9 // add	x9, x14, #4
	WORD $0x39000dcf // strb	w15, [x14, #3]
	WORD $0xaa0903ee // mov	x14, x9
	WORD $0xeb0d017f // cmp	x11, x13
	WORD $0x54fffde9 // b.ls	84 // LBB0_4

	// LBB0_5:
	WORD $0xcb0b018e // sub	x14, x12, x11
	WORD $0x3940016c // ldrb	w12, [x11]
	WORD $0xf10005df // cmp	x14, #1
	WORD $0x540004e0 // b.eq	324 // LBB0_11
	WORD $0xd370bd8d // lsl	x13, x12, #16
	WORD $0xf10009df // cmp	x14, #2
	WORD $0x54000280 // b.eq	260 // LBB0_9
	WORD $0xf1000ddf // cmp	x14, #3
	WORD $0x54000621 // b.ne	384 // LBB0_16
	WORD $0x3940096e // ldrb	w14, [x11, #2]
	WORD $0xaa0e01ad // orr	x13, x13, x14
	WORD $0x3940056b // ldrb	w11, [x11, #1]
	WORD $0xaa0b21ab // orr	x11, x13, x11, lsl #8
	WORD $0xd34c456d // ubfx	x13, x11, #12, #6
	WORD $0xd342fd8c // lsr	x12, x12, #2
	WORD $0x386c694c // ldrb	w12, [x10, x12]
	WORD $0x386d694d // ldrb	w13, [x10, x13]
	WORD $0x3900012c // strb	w12, [x9]
	WORD $0x3900052d // strb	w13, [x9, #1]
	WORD $0xd3462d6b // ubfx	x11, x11, #6, #6
	WORD $0x386b694b // ldrb	w11, [x10, x11]
	WORD $0x3900092b // strb	w11, [x9, #2]
	WORD $0x924015cb // and	x11, x14, #0x3f
	WORD $0x386b694a // ldrb	w10, [x10, x11]
	WORD $0x39000d2a // strb	w10, [x9, #3]
	WORD $0x1400001b // b	364 // LBB0_13

	// LBB0_9:
	WORD $0x3940056b // ldrb	w11, [x11, #1]
	WORD $0x2a0b21ad // orr	w13, w13, w11, lsl #8
	WORD $0xd342fd8c // lsr	x12, x12, #2
	WORD $0x386c694c // ldrb	w12, [x10, x12]
	WORD $0x3900012c // strb	w12, [x9]
	WORD $0xd34c45ac // ubfx	x12, x13, #12, #6
	WORD $0x386c694c // ldrb	w12, [x10, x12]
	WORD $0x3900052c // strb	w12, [x9, #1]
	WORD $0x531e756b // lsl	w11, w11, #2
	WORD $0x927e0d6b // and	x11, x11, #0x3c
	WORD $0x386b694a // ldrb	w10, [x10, x11]
	WORD $0x3900092a // strb	w10, [x9, #2]
	WORD $0x37080202 // tbnz	w2, #1, 372 // LBB0_14
	WORD $0x528007aa // mov	w10, #61
	WORD $0x39000d2a // strb	w10, [x9, #3]
	WORD $0x1400000b // b	364 // LBB0_13

	// LBB0_11:
	WORD $0xd342fd8b // lsr	x11, x12, #2
	WORD $0x386b694b // ldrb	w11, [x10, x11]
	WORD $0x3900012b // strb	w11, [x9]
	WORD $0x531c6d8b // lsl	w11, w12, #4
	WORD $0x927c056b // and	x11, x11, #0x30
	WORD $0x386b694a // ldrb	w10, [x10, x11]
	WORD $0x3900052a // strb	w10, [x9, #1]
	WORD $0x370800e2 // tbnz	w2, #1, 380 // LBB0_15
	WORD $0x5287a7aa // mov	w10, #15677
	WORD $0x7900052a // strh	w10, [x9, #2]

	// LBB0_13:
	WORD $0x91001129 // add	x9, x9, #4
	WORD $0x14000004 // b	384 // LBB0_16

	// LBB0_14:
	WORD $0x91000d29 // add	x9, x9, #3
	WORD $0x14000002 // b	384 // LBB0_16

	// LBB0_15:
	WORD $0x91000929 // add	x9, x9, #2

	// LBB0_16:
	WORD $0xf940040a // ldr	x10, [x0, #8]
	WORD $0xcb080128 // sub	x8, x9, x8
	WORD $0x8b0a0108 // add	x8, x8, x10
	WORD $0xf9000408 // str	x8, [x0, #8]

	// LBB0_17:
	WORD $0xd65f03c0 // ret

	// _b64decode:
	WORD $0xa9bd5ff8 // stp	x24, x23, [sp, #-48]!
	WORD $0xa90157f6 // stp	x22, x21, [sp, #16]
	WORD $0xa9024ff4 // stp	x20, x19, [sp, #32]
	WORD $0xb4001642 // cbz	x2, 1128 // LBB1_42
	WORD $0xa9402009 // ldp	x9, x8, [x0]
	WORD $0x8b080128 // add	x8, x9, x8
	WORD $0xf940080a // ldr	x10, [x0, #16]
	WORD $0x8b0a012f // add	x15, x9, x10
	WORD $0x8b020029 // add	x9, x1, x2
	WORD $0x9000000a // adrp	x10, 0 // _VecDecodeCharsetURL
	WORD $0x912d214a // add	x10, x10, 2888 // _VecDecodeCharsetURL
	WORD $0x9000000b // adrp	x11, 0 // _VecDecodeCharsetStd
	WORD $0x9129216b // add	x11, x11, 2632 // _VecDecodeCharsetStd
	WORD $0x7200007f // tst	w3, #0x1
	WORD $0x9a8a016a // csel	x10, x11, x10, eq
	WORD $0xd1002130 // sub	x16, x9, #8
	WORD $0xd100052b // sub	x11, x9, #1
	WORD $0x9100052e // add	x14, x9, #1
	WORD $0xeb01021f // cmp	x16, x1
	WORD $0x54001503 // b.lo	1152 // LBB1_43
	WORD $0xd10021f1 // sub	x17, x15, #8
	WORD $0xeb11011f // cmp	x8, x17
	WORD $0x540014a8 // b.hi	1152 // LBB1_43
	WORD $0x52800082 // mov	w2, #4
	WORD $0xaa0103ed // mov	x13, x1
	WORD $0xaa0803ec // mov	x12, x8

	// LBB1_4:
	WORD $0x394001a7 // ldrb	w7, [x13]
	WORD $0x38676944 // ldrb	w4, [x10, x7]
	WORD $0x394005a5 // ldrb	w5, [x13, #1]
	WORD $0x38656945 // ldrb	w5, [x10, x5]
	WORD $0x394009a6 // ldrb	w6, [x13, #2]
	WORD $0x38666946 // ldrb	w6, [x10, x6]
	WORD $0x39400db3 // ldrb	w19, [x13, #3]
	WORD $0x38736953 // ldrb	w19, [x10, x19]
	WORD $0x394011b4 // ldrb	w20, [x13, #4]
	WORD $0x38746954 // ldrb	w20, [x10, x20]
	WORD $0x394015b5 // ldrb	w21, [x13, #5]
	WORD $0x38756955 // ldrb	w21, [x10, x21]
	WORD $0x394019b6 // ldrb	w22, [x13, #6]
	WORD $0x38766956 // ldrb	w22, [x10, x22]
	WORD $0x39401db7 // ldrb	w23, [x13, #7]
	WORD $0x38776957 // ldrb	w23, [x10, x23]
	WORD $0x2a0400b8 // orr	w24, w5, w4
	WORD $0x2a060318 // orr	w24, w24, w6
	WORD $0x2a130318 // orr	w24, w24, w19
	WORD $0x2a140318 // orr	w24, w24, w20
	WORD $0x2a150318 // orr	w24, w24, w21
	WORD $0x2a160318 // orr	w24, w24, w22
	WORD $0x2a170318 // orr	w24, w24, w23
	WORD $0x2a3803f8 // mvn	w24, w24
	WORD $0x72001f1f // tst	w24, #0xff
	WORD $0x54000401 // b.ne	736 // LBB1_13
	WORD $0xeb0901bf // cmp	x13, x9
	WORD $0x54000582 // b.hs	792 // LBB1_14
	WORD $0x52800005 // mov	w5, #0
	WORD $0x52800004 // mov	w4, #0
	WORD $0x910005a6 // add	x6, x13, #1
	WORD $0x12001cf3 // and	w19, w7, #0xff
	WORD $0x71002a7f // cmp	w19, #10
	WORD $0x7a4d1a64 // ccmp	w19, #13, #4, ne
	WORD $0x54000200 // b.eq	708 // LBB1_10
	WORD $0x14000006 // b	672 // LBB1_8

	// LBB1_7:
	WORD $0x384014c7 // ldrb	w7, [x6], #1
	WORD $0x12001cf3 // and	w19, w7, #0xff
	WORD $0x71002a7f // cmp	w19, #10
	WORD $0x7a4d1a64 // ccmp	w19, #13, #4, ne
	WORD $0x54000140 // b.eq	708 // LBB1_10

	// LBB1_8:
	WORD $0x92401ce7 // and	x7, x7, #0xff
	WORD $0x38676947 // ldrb	w7, [x10, x7]
	WORD $0x7103fcff // cmp	w7, #255
	WORD $0x54000580 // b.eq	860 // LBB1_19
	WORD $0x110004a5 // add	w5, w5, #1
	WORD $0x2a0418e4 // orr	w4, w7, w4, lsl #6
	WORD $0x71000cbf // cmp	w5, #3
	WORD $0x5400008d // b.le	716 // LBB1_11
	WORD $0x14000005 // b	724 // LBB1_12

	// LBB1_10:
	WORD $0x71000cbf // cmp	w5, #3
	WORD $0x5400006c // b.gt	724 // LBB1_12

	// LBB1_11:
	WORD $0xeb0900df // cmp	x6, x9
	WORD $0x54fffde3 // b.lo	652 // LBB1_7

	// LBB1_12:
	WORD $0x710004bf // cmp	w5, #1
	WORD $0x54000581 // b.ne	904 // LBB1_23
	WORD $0x14000023 // b	872 // LBB1_20

	// LBB1_13:
	WORD $0xd34c2ca5 // lsl	x5, x5, #52
	WORD $0xaa04e8a4 // orr	x4, x5, x4, lsl #58
	WORD $0xaa06b884 // orr	x4, x4, x6, lsl #46
	WORD $0xaa13a084 // orr	x4, x4, x19, lsl #40
	WORD $0xaa148884 // orr	x4, x4, x20, lsl #34
	WORD $0xaa157084 // orr	x4, x4, x21, lsl #28
	WORD $0xaa165884 // orr	x4, x4, x22, lsl #22
	WORD $0xaa174084 // orr	x4, x4, x23, lsl #16
	WORD $0xdac00c84 // rev	x4, x4
	WORD $0xf8006584 // str	x4, [x12], #6
	WORD $0x910021ad // add	x13, x13, #8
	WORD $0xeb1001bf // cmp	x13, x16
	WORD $0x54000369 // b.ls	892 // LBB1_22
	WORD $0x1400005d // b	1160 // LBB1_44

	// LBB1_14:
	WORD $0x52800005 // mov	w5, #0
	WORD $0x52800004 // mov	w4, #0
	WORD $0xaa0d03e6 // mov	x6, x13
	WORD $0x54000540 // b.eq	972 // LBB1_30

	// LBB1_15:
	WORD $0xeb0b00df // cmp	x6, x11
	WORD $0x540001e2 // b.hs	872 // LBB1_20
	WORD $0xaa0603e7 // mov	x7, x6
	WORD $0x384014f3 // ldrb	w19, [x7], #1
	WORD $0x7100f67f // cmp	w19, #61
	WORD $0x540000a1 // b.ne	848 // LBB1_18
	WORD $0x910008c7 // add	x7, x6, #2
	WORD $0x394004c6 // ldrb	w6, [x6, #1]
	WORD $0x7100f4df // cmp	w6, #61
	WORD $0x54000340 // b.eq	948 // LBB1_28

	// LBB1_18:
	WORD $0xcb0d00e4 // sub	x4, x7, x13
	WORD $0xb4000104 // cbz	x4, 884 // LBB1_21
	WORD $0x1400003d // b	1100 // LBB1_41

	// LBB1_19:
	WORD $0xd10004c6 // sub	x6, x6, #1
	WORD $0x710004bf // cmp	w5, #1
	WORD $0x54000121 // b.ne	904 // LBB1_23

	// LBB1_20:
	WORD $0xcb0d00c4 // sub	x4, x6, x13
	WORD $0x91000484 // add	x4, x4, #1
	WORD $0xb50006e4 // cbnz	x4, 1100 // LBB1_41

	// LBB1_21:
	WORD $0xeb1001bf // cmp	x13, x16
	WORD $0x54000888 // b.hi	1160 // LBB1_44

	// LBB1_22:
	WORD $0xeb11019f // cmp	x12, x17
	WORD $0x54fff3e9 // b.ls	508 // LBB1_4
	WORD $0x14000041 // b	1160 // LBB1_44

	// LBB1_23:
	WORD $0x71000cbf // cmp	w5, #3
	WORD $0x540003ac // b.gt	1024 // LBB1_33
	WORD $0xeb0900df // cmp	x6, x9
	WORD $0x540001c0 // b.eq	972 // LBB1_30
	WORD $0x71000cbf // cmp	w5, #3
	WORD $0x54fffc61 // b.ne	808 // LBB1_15
	WORD $0x384014c5 // ldrb	w5, [x6], #1
	WORD $0x7100f4bf // cmp	w5, #61
	WORD $0x540004e1 // b.ne	1092 // LBB1_40
	WORD $0x52800065 // mov	w5, #3
	WORD $0xaa0603e7 // mov	x7, x6

	// LBB1_28:
	WORD $0xeb0900ff // cmp	x7, x9
	WORD $0x54000142 // b.hs	992 // LBB1_32
	WORD $0xcb0d00e4 // sub	x4, x7, x13
	WORD $0x91000484 // add	x4, x4, #1
	WORD $0xb4fffd84 // cbz	x4, 884 // LBB1_21
	WORD $0x14000021 // b	1100 // LBB1_41

	// LBB1_30:
	WORD $0xaa0903e7 // mov	x7, x9
	WORD $0x37080083 // tbnz	w3, #1, 992 // LBB1_32
	WORD $0xcb0d01c4 // sub	x4, x14, x13
	WORD $0xb4fffce4 // cbz	x4, 884 // LBB1_21
	WORD $0x1400001c // b	1100 // LBB1_41

	// LBB1_32:
	WORD $0x4b05004d // sub	w13, w2, w5
	WORD $0xb0d05ad  // add	w13, w13, w13, lsl #1
	WORD $0x531f79ad // lsl	w13, w13, #1
	WORD $0x1acd2084 // lsl	w4, w4, w13
	WORD $0xaa0703ed // mov	x13, x7
	WORD $0x710008bf // cmp	w5, #2
	WORD $0x540000a1 // b.ne	1036 // LBB1_34
	WORD $0x1400000b // b	1064 // LBB1_38

	// LBB1_33:
	WORD $0xaa0603ed // mov	x13, x6
	WORD $0x710008bf // cmp	w5, #2
	WORD $0x54000100 // b.eq	1064 // LBB1_38

	// LBB1_34:
	WORD $0x71000cbf // cmp	w5, #3
	WORD $0x54000080 // b.eq	1056 // LBB1_37
	WORD $0x710010bf // cmp	w5, #4
	WORD $0x540000c1 // b.ne	1072 // LBB1_39
	WORD $0x39000984 // strb	w4, [x12, #2]

	// LBB1_37:
	WORD $0x53087c86 // lsr	w6, w4, #8
	WORD $0x39000586 // strb	w6, [x12, #1]

	// LBB1_38:
	WORD $0x53107c84 // lsr	w4, w4, #16
	WORD $0x39000184 // strb	w4, [x12]

	// LBB1_39:
	WORD $0x8b25c18c // add	x12, x12, w5, sxtw
	WORD $0xd100058c // sub	x12, x12, #1
	WORD $0xeb1001bf // cmp	x13, x16
	WORD $0x54fffa09 // b.ls	892 // LBB1_22
	WORD $0x14000012 // b	1160 // LBB1_44

	// LBB1_40:
	WORD $0xcb0d00c4 // sub	x4, x6, x13
	WORD $0xb4fff964 // cbz	x4, 884 // LBB1_21

	// LBB1_41:
	WORD $0x8b0d0088 // add	x8, x4, x13
	WORD $0xcb080028 // sub	x8, x1, x8
	WORD $0xaa0803e0 // mov	x0, x8
	WORD $0xa9424ff4 // ldp	x20, x19, [sp, #32]
	WORD $0xa94157f6 // ldp	x22, x21, [sp, #16]
	WORD $0xa8c35ff8 // ldp	x24, x23, [sp], #48
	WORD $0xd65f03c0 // ret

	// LBB1_42:
	WORD $0xd2800008 // mov	x8, #0
	WORD $0xaa0803e0 // mov	x0, x8
	WORD $0xa9424ff4 // ldp	x20, x19, [sp, #32]
	WORD $0xa94157f6 // ldp	x22, x21, [sp, #16]
	WORD $0xa8c35ff8 // ldp	x24, x23, [sp], #48
	WORD $0xd65f03c0 // ret

	// LBB1_43:
	WORD $0xaa0803ec // mov	x12, x8
	WORD $0xaa0103ed // mov	x13, x1

	// LBB1_44:
	WORD $0xd1001130 // sub	x16, x9, #4
	WORD $0xeb1001bf // cmp	x13, x16
	WORD $0x540011e8 // b.hi	1740 // LBB1_85
	WORD $0xd10011ef // sub	x15, x15, #4
	WORD $0xeb0f019f // cmp	x12, x15
	WORD $0x54001188 // b.hi	1740 // LBB1_85
	WORD $0x52800091 // mov	w17, #4

	// LBB1_47:
	WORD $0x394001a6 // ldrb	w6, [x13]
	WORD $0x38666942 // ldrb	w2, [x10, x6]
	WORD $0x394005a4 // ldrb	w4, [x13, #1]
	WORD $0x38646944 // ldrb	w4, [x10, x4]
	WORD $0x394009a5 // ldrb	w5, [x13, #2]
	WORD $0x38656945 // ldrb	w5, [x10, x5]
	WORD $0x39400da7 // ldrb	w7, [x13, #3]
	WORD $0x38676947 // ldrb	w7, [x10, x7]
	WORD $0x2a020093 // orr	w19, w4, w2
	WORD $0x2a050273 // orr	w19, w19, w5
	WORD $0x2a070273 // orr	w19, w19, w7
	WORD $0x7103fe7f // cmp	w19, #255
	WORD $0x54000401 // b.ne	1364 // LBB1_56
	WORD $0xeb0901bf // cmp	x13, x9
	WORD $0x54000502 // b.hs	1404 // LBB1_57
	WORD $0x52800004 // mov	w4, #0
	WORD $0x52800002 // mov	w2, #0
	WORD $0x910005a5 // add	x5, x13, #1
	WORD $0x12001cc7 // and	w7, w6, #0xff
	WORD $0x710028ff // cmp	w7, #10
	WORD $0x7a4d18e4 // ccmp	w7, #13, #4, ne
	WORD $0x54000200 // b.eq	1336 // LBB1_53
	WORD $0x14000006 // b	1300 // LBB1_51

	// LBB1_50:
	WORD $0x384014a6 // ldrb	w6, [x5], #1
	WORD $0x12001cc7 // and	w7, w6, #0xff
	WORD $0x710028ff // cmp	w7, #10
	WORD $0x7a4d18e4 // ccmp	w7, #13, #4, ne
	WORD $0x54000140 // b.eq	1336 // LBB1_53

	// LBB1_51:
	WORD $0x92401cc6 // and	x6, x6, #0xff
	WORD $0x38666946 // ldrb	w6, [x10, x6]
	WORD $0x7103fcdf // cmp	w6, #255
	WORD $0x54000500 // b.eq	1472 // LBB1_62
	WORD $0x11000484 // add	w4, w4, #1
	WORD $0x2a0218c2 // orr	w2, w6, w2, lsl #6
	WORD $0x71000c9f // cmp	w4, #3
	WORD $0x5400008d // b.le	1344 // LBB1_54
	WORD $0x14000005 // b	1352 // LBB1_55

	// LBB1_53:
	WORD $0x71000c9f // cmp	w4, #3
	WORD $0x5400006c // b.gt	1352 // LBB1_55

	// LBB1_54:
	WORD $0xeb0900bf // cmp	x5, x9
	WORD $0x54fffde3 // b.lo	1280 // LBB1_50

	// LBB1_55:
	WORD $0x7100049f // cmp	w4, #1
	WORD $0x54000501 // b.ne	1516 // LBB1_66
	WORD $0x1400001f // b	1484 // LBB1_63

	// LBB1_56:
	WORD $0x530c2c84 // lsl	w4, w4, #20
	WORD $0x2a026882 // orr	w2, w4, w2, lsl #26
	WORD $0x2a053842 // orr	w2, w2, w5, lsl #14
	WORD $0x2a072042 // orr	w2, w2, w7, lsl #8
	WORD $0x5ac00842 // rev	w2, w2
	WORD $0xb8003582 // str	w2, [x12], #3
	WORD $0x910011ad // add	x13, x13, #4
	WORD $0xeb1001bf // cmp	x13, x16
	WORD $0x54000369 // b.ls	1504 // LBB1_65
	WORD $0x14000055 // b	1740 // LBB1_85

	// LBB1_57:
	WORD $0x52800004 // mov	w4, #0
	WORD $0x52800002 // mov	w2, #0
	WORD $0xaa0d03e5 // mov	x5, x13
	WORD $0x54000540 // b.eq	1584 // LBB1_73

	// LBB1_58:
	WORD $0xeb0b00bf // cmp	x5, x11
	WORD $0x540001e2 // b.hs	1484 // LBB1_63
	WORD $0xaa0503e6 // mov	x6, x5
	WORD $0x384014c7 // ldrb	w7, [x6], #1
	WORD $0x7100f4ff // cmp	w7, #61
	WORD $0x540000a1 // b.ne	1460 // LBB1_61
	WORD $0x910008a6 // add	x6, x5, #2
	WORD $0x394004a5 // ldrb	w5, [x5, #1]
	WORD $0x7100f4bf // cmp	w5, #61
	WORD $0x54000340 // b.eq	1560 // LBB1_71

	// LBB1_61:
	WORD $0xcb0d00c2 // sub	x2, x6, x13
	WORD $0xb4000102 // cbz	x2, 1496 // LBB1_64
	WORD $0x1400003d // b	1712 // LBB1_84

	// LBB1_62:
	WORD $0xd10004a5 // sub	x5, x5, #1
	WORD $0x7100049f // cmp	w4, #1
	WORD $0x54000121 // b.ne	1516 // LBB1_66

	// LBB1_63:
	WORD $0xcb0d00a2 // sub	x2, x5, x13
	WORD $0x91000442 // add	x2, x2, #1
	WORD $0xb50006e2 // cbnz	x2, 1712 // LBB1_84

	// LBB1_64:
	WORD $0xeb1001bf // cmp	x13, x16
	WORD $0x54000788 // b.hi	1740 // LBB1_85

	// LBB1_65:
	WORD $0xeb0f019f // cmp	x12, x15
	WORD $0x54fff609 // b.ls	1188 // LBB1_47
	WORD $0x14000039 // b	1740 // LBB1_85

	// LBB1_66:
	WORD $0x71000c9f // cmp	w4, #3
	WORD $0x540003ac // b.gt	1636 // LBB1_76
	WORD $0xeb0900bf // cmp	x5, x9
	WORD $0x540001c0 // b.eq	1584 // LBB1_73
	WORD $0x71000c9f // cmp	w4, #3
	WORD $0x54fffc61 // b.ne	1420 // LBB1_58
	WORD $0x384014a4 // ldrb	w4, [x5], #1
	WORD $0x7100f49f // cmp	w4, #61
	WORD $0x540004e1 // b.ne	1704 // LBB1_83
	WORD $0x52800064 // mov	w4, #3
	WORD $0xaa0503e6 // mov	x6, x5

	// LBB1_71:
	WORD $0xeb0900df // cmp	x6, x9
	WORD $0x54000142 // b.hs	1604 // LBB1_75
	WORD $0xcb0d00c2 // sub	x2, x6, x13
	WORD $0x91000442 // add	x2, x2, #1
	WORD $0xb4fffd82 // cbz	x2, 1496 // LBB1_64
	WORD $0x14000021 // b	1712 // LBB1_84

	// LBB1_73:
	WORD $0xaa0903e6 // mov	x6, x9
	WORD $0x37080083 // tbnz	w3, #1, 1604 // LBB1_75
	WORD $0xcb0d01c2 // sub	x2, x14, x13
	WORD $0xb4fffce2 // cbz	x2, 1496 // LBB1_64
	WORD $0x1400001c // b	1712 // LBB1_84

	// LBB1_75:
	WORD $0x4b04022d // sub	w13, w17, w4
	WORD $0xb0d05ad  // add	w13, w13, w13, lsl #1
	WORD $0x531f79ad // lsl	w13, w13, #1
	WORD $0x1acd2042 // lsl	w2, w2, w13
	WORD $0xaa0603ed // mov	x13, x6
	WORD $0x7100089f // cmp	w4, #2
	WORD $0x540000a1 // b.ne	1648 // LBB1_77
	WORD $0x1400000b // b	1676 // LBB1_81

	// LBB1_76:
	WORD $0xaa0503ed // mov	x13, x5
	WORD $0x7100089f // cmp	w4, #2
	WORD $0x54000100 // b.eq	1676 // LBB1_81

	// LBB1_77:
	WORD $0x71000c9f // cmp	w4, #3
	WORD $0x54000080 // b.eq	1668 // LBB1_80
	WORD $0x7100109f // cmp	w4, #4
	WORD $0x540000c1 // b.ne	1684 // LBB1_82
	WORD $0x39000982 // strb	w2, [x12, #2]

	// LBB1_80:
	WORD $0x53087c45 // lsr	w5, w2, #8
	WORD $0x39000585 // strb	w5, [x12, #1]

	// LBB1_81:
	WORD $0x53107c42 // lsr	w2, w2, #16
	WORD $0x39000182 // strb	w2, [x12]

	// LBB1_82:
	WORD $0x8b24c18c // add	x12, x12, w4, sxtw
	WORD $0xd100058c // sub	x12, x12, #1
	WORD $0xeb1001bf // cmp	x13, x16
	WORD $0x54fffa09 // b.ls	1504 // LBB1_65
	WORD $0x1400000a // b	1740 // LBB1_85

	// LBB1_83:
	WORD $0xcb0d00a2 // sub	x2, x5, x13
	WORD $0xb4fff962 // cbz	x2, 1496 // LBB1_64

	// LBB1_84:
	WORD $0x8b0d0048 // add	x8, x2, x13
	WORD $0xcb080028 // sub	x8, x1, x8
	WORD $0xaa0803e0 // mov	x0, x8
	WORD $0xa9424ff4 // ldp	x20, x19, [sp, #32]
	WORD $0xa94157f6 // ldp	x22, x21, [sp, #16]
	WORD $0xa8c35ff8 // ldp	x24, x23, [sp], #48
	WORD $0xd65f03c0 // ret

	// LBB1_85:
	WORD $0x37080b43 // tbnz	w3, #1, 2100 // LBB1_116
	WORD $0x5280008f // mov	w15, #4
	WORD $0x14000004 // b	1764 // LBB1_88

	// LBB1_87:
	WORD $0xcb0d0050 // sub	x16, x2, x13
	WORD $0x91000610 // add	x16, x16, #1
	WORD $0xb5001670 // cbnz	x16, 2476 // LBB1_149

	// LBB1_88:
	WORD $0xeb0901bf // cmp	x13, x9
	WORD $0x540014e2 // b.hs	2436 // LBB1_147
	WORD $0x52800010 // mov	w16, #0
	WORD $0x52800011 // mov	w17, #0
	WORD $0xaa0d03e2 // mov	x2, x13

	// LBB1_90:
	WORD $0x39400043 // ldrb	w3, [x2]
	WORD $0x7100287f // cmp	w3, #10
	WORD $0x7a4d1864 // ccmp	w3, #13, #4, ne
	WORD $0x540000a1 // b.ne	1816 // LBB1_92
	WORD $0x91000442 // add	x2, x2, #1
	WORD $0x71000e1f // cmp	w16, #3
	WORD $0x5400014d // b.le	1848 // LBB1_94
	WORD $0x1400000b // b	1856 // LBB1_95

	// LBB1_92:
	WORD $0x38636943 // ldrb	w3, [x10, x3]
	WORD $0x7103fc7f // cmp	w3, #255
	WORD $0x54000100 // b.eq	1856 // LBB1_95
	WORD $0x11000610 // add	w16, w16, #1
	WORD $0x2a111871 // orr	w17, w3, w17, lsl #6
	WORD $0x91000442 // add	x2, x2, #1
	WORD $0x71000e1f // cmp	w16, #3
	WORD $0x5400006c // b.gt	1856 // LBB1_95

	// LBB1_94:
	WORD $0xeb09005f // cmp	x2, x9
	WORD $0x54fffde3 // b.lo	1784 // LBB1_90

	// LBB1_95:
	WORD $0x7100061f // cmp	w16, #1
	WORD $0x54fffca0 // b.eq	1752 // LBB1_87
	WORD $0x71000e1f // cmp	w16, #3
	WORD $0x5400018c // b.gt	1916 // LBB1_101
	WORD $0xeb09005f // cmp	x2, x9
	WORD $0x54000340 // b.eq	1980 // LBB1_108
	WORD $0x71000e1f // cmp	w16, #3
	WORD $0x54000361 // b.ne	1992 // LBB1_109
	WORD $0x38401444 // ldrb	w4, [x2], #1
	WORD $0xaa0203e3 // mov	x3, x2
	WORD $0x7100f49f // cmp	w4, #61
	WORD $0x54000420 // b.eq	2032 // LBB1_112
	WORD $0xcb0d0050 // sub	x16, x2, x13
	WORD $0xb4fffb90 // cbz	x16, 1764 // LBB1_88
	WORD $0x1400008d // b	2476 // LBB1_149

	// LBB1_101:
	WORD $0xaa0203ed // mov	x13, x2
	WORD $0x71000a1f // cmp	w16, #2
	WORD $0x54000100 // b.eq	1956 // LBB1_106

	// LBB1_102:
	WORD $0x71000e1f // cmp	w16, #3
	WORD $0x54000080 // b.eq	1948 // LBB1_105
	WORD $0x7100121f // cmp	w16, #4
	WORD $0x540000c1 // b.ne	1964 // LBB1_107
	WORD $0x39000991 // strb	w17, [x12, #2]

	// LBB1_105:
	WORD $0x53087e22 // lsr	w2, w17, #8
	WORD $0x39000582 // strb	w2, [x12, #1]

	// LBB1_106:
	WORD $0x53107e31 // lsr	w17, w17, #16
	WORD $0x39000191 // strb	w17, [x12]

	// LBB1_107:
	WORD $0x8b30c18c // add	x12, x12, w16, sxtw
	WORD $0xd100058c // sub	x12, x12, #1
	WORD $0xb4fff99f // cbz	xzr, 1764 // LBB1_88
	WORD $0x1400007c // b	2472 // LBB1_148

	// LBB1_108:
	WORD $0xcb0d01d0 // sub	x16, x14, x13
	WORD $0xb4fff930 // cbz	x16, 1764 // LBB1_88
	WORD $0x1400007a // b	2476 // LBB1_149

	// LBB1_109:
	WORD $0xeb0b005f // cmp	x2, x11
	WORD $0x54fff862 // b.hs	1752 // LBB1_87
	WORD $0xaa0203e3 // mov	x3, x2
	WORD $0x38401464 // ldrb	w4, [x3], #1
	WORD $0x7100f49f // cmp	w4, #61
	WORD $0x54000161 // b.ne	2056 // LBB1_114
	WORD $0x91000843 // add	x3, x2, #2
	WORD $0x39400442 // ldrb	w2, [x2, #1]
	WORD $0x7100f45f // cmp	w2, #61
	WORD $0x540000e1 // b.ne	2056 // LBB1_114

	// LBB1_112:
	WORD $0xeb09007f // cmp	x3, x9
	WORD $0x54000102 // b.hs	2068 // LBB1_115
	WORD $0xcb0d0070 // sub	x16, x3, x13
	WORD $0x91000610 // add	x16, x16, #1
	WORD $0xb4fff730 // cbz	x16, 1764 // LBB1_88
	WORD $0x1400006a // b	2476 // LBB1_149

	// LBB1_114:
	WORD $0xcb0d0070 // sub	x16, x3, x13
	WORD $0xb4fff6d0 // cbz	x16, 1764 // LBB1_88
	WORD $0x14000067 // b	2476 // LBB1_149

	// LBB1_115:
	WORD $0x4b1001ed // sub	w13, w15, w16
	WORD $0xb0d05ad  // add	w13, w13, w13, lsl #1
	WORD $0x531f79ad // lsl	w13, w13, #1
	WORD $0x1acd2231 // lsl	w17, w17, w13
	WORD $0xaa0303ed // mov	x13, x3
	WORD $0x71000a1f // cmp	w16, #2
	WORD $0x54fffae1 // b.ne	1928 // LBB1_102
	WORD $0x17ffffdd // b	1956 // LBB1_106

	// LBB1_116:
	WORD $0x5280008e // mov	w14, #4
	WORD $0x14000009 // b	2140 // LBB1_121

	// LBB1_117:
	WORD $0x53087e11 // lsr	w17, w16, #8
	WORD $0x39000591 // strb	w17, [x12, #1]

	// LBB1_118:
	WORD $0x53107e10 // lsr	w16, w16, #16
	WORD $0x39000190 // strb	w16, [x12]

	// LBB1_119:
	WORD $0xd2800010 // mov	x16, #0
	WORD $0x8b2fc18c // add	x12, x12, w15, sxtw
	WORD $0xd100058c // sub	x12, x12, #1

	// LBB1_120:
	WORD $0xb5000ab0 // cbnz	x16, 2476 // LBB1_149

	// LBB1_121:
	WORD $0xeb0901bf // cmp	x13, x9
	WORD $0x54000922 // b.hs	2436 // LBB1_147
	WORD $0x5280000f // mov	w15, #0
	WORD $0x52800010 // mov	w16, #0
	WORD $0xaa0d03f1 // mov	x17, x13

	// LBB1_123:
	WORD $0x39400222 // ldrb	w2, [x17]
	WORD $0x7100285f // cmp	w2, #10
	WORD $0x7a4d1844 // ccmp	w2, #13, #4, ne
	WORD $0x540000a1 // b.ne	2192 // LBB1_125
	WORD $0x91000631 // add	x17, x17, #1
	WORD $0x71000dff // cmp	w15, #3
	WORD $0x5400014d // b.le	2224 // LBB1_127
	WORD $0x1400000b // b	2232 // LBB1_128

	// LBB1_125:
	WORD $0x38626942 // ldrb	w2, [x10, x2]
	WORD $0x7103fc5f // cmp	w2, #255
	WORD $0x54000100 // b.eq	2232 // LBB1_128
	WORD $0x110005ef // add	w15, w15, #1
	WORD $0x2a101850 // orr	w16, w2, w16, lsl #6
	WORD $0x91000631 // add	x17, x17, #1
	WORD $0x71000dff // cmp	w15, #3
	WORD $0x5400006c // b.gt	2232 // LBB1_128

	// LBB1_127:
	WORD $0xeb09023f // cmp	x17, x9
	WORD $0x54fffde3 // b.lo	2160 // LBB1_123

	// LBB1_128:
	WORD $0x710005ff // cmp	w15, #1
	WORD $0x54000081 // b.ne	2252 // LBB1_131

	// LBB1_129:
	WORD $0xcb0d022f // sub	x15, x17, x13

	// LBB1_130:
	WORD $0x910005f0 // add	x16, x15, #1
	WORD $0x17ffffe4 // b	2136 // LBB1_120

	// LBB1_131:
	WORD $0x71000dff // cmp	w15, #3
	WORD $0x5400018c // b.gt	2304 // LBB1_136
	WORD $0xaa0903e2 // mov	x2, x9
	WORD $0xeb09023f // cmp	x17, x9
	WORD $0x54000360 // b.eq	2376 // LBB1_142
	WORD $0x71000dff // cmp	w15, #3
	WORD $0x54000161 // b.ne	2320 // LBB1_137
	WORD $0x38401623 // ldrb	w3, [x17], #1
	WORD $0xaa1103e2 // mov	x2, x17
	WORD $0x7100f47f // cmp	w3, #61
	WORD $0x54000220 // b.eq	2360 // LBB1_140
	WORD $0xcb0d0230 // sub	x16, x17, x13
	WORD $0x17ffffd7 // b	2136 // LBB1_120

	// LBB1_136:
	WORD $0xaa1103ed // mov	x13, x17
	WORD $0x710009ff // cmp	w15, #2
	WORD $0x540002e1 // b.ne	2404 // LBB1_143
	WORD $0x17ffffce // b	2116 // LBB1_118

	// LBB1_137:
	WORD $0xeb0b023f // cmp	x17, x11
	WORD $0x54fffd62 // b.hs	2240 // LBB1_129
	WORD $0xaa1103e2 // mov	x2, x17
	WORD $0x38401443 // ldrb	w3, [x2], #1
	WORD $0x7100f47f // cmp	w3, #61
	WORD $0x540002c1 // b.ne	2428 // LBB1_146
	WORD $0x91000a22 // add	x2, x17, #2
	WORD $0x39400631 // ldrb	w17, [x17, #1]
	WORD $0x7100f63f // cmp	w17, #61
	WORD $0x54000241 // b.ne	2428 // LBB1_146

	// LBB1_140:
	WORD $0xeb09005f // cmp	x2, x9
	WORD $0x54000062 // b.hs	2376 // LBB1_142
	WORD $0xcb0d004f // sub	x15, x2, x13
	WORD $0x17ffffe0 // b	2244 // LBB1_130

	// LBB1_142:
	WORD $0x4b0f01cd // sub	w13, w14, w15
	WORD $0xb0d05ad  // add	w13, w13, w13, lsl #1
	WORD $0x531f79ad // lsl	w13, w13, #1
	WORD $0x1acd2210 // lsl	w16, w16, w13
	WORD $0xaa0203ed // mov	x13, x2
	WORD $0x710009ff // cmp	w15, #2
	WORD $0x54fff720 // b.eq	2116 // LBB1_118

	// LBB1_143:
	WORD $0x71000dff // cmp	w15, #3
	WORD $0x54fff6a0 // b.eq	2108 // LBB1_117
	WORD $0x710011ff // cmp	w15, #4
	WORD $0x54fff6e1 // b.ne	2124 // LBB1_119
	WORD $0x39000990 // strb	w16, [x12, #2]
	WORD $0x17ffffb1 // b	2108 // LBB1_117

	// LBB1_146:
	WORD $0xcb0d0050 // sub	x16, x2, x13
	WORD $0x17ffffb6 // b	2136 // LBB1_120

	// LBB1_147:
	WORD $0xf9400409 // ldr	x9, [x0, #8]
	WORD $0xcb080188 // sub	x8, x12, x8
	WORD $0x8b080129 // add	x9, x9, x8
	WORD $0xf9000409 // str	x9, [x0, #8]
	WORD $0xaa0803e0 // mov	x0, x8
	WORD $0xa9424ff4 // ldp	x20, x19, [sp, #32]
	WORD $0xa94157f6 // ldp	x22, x21, [sp, #16]
	WORD $0xa8c35ff8 // ldp	x24, x23, [sp], #48
	WORD $0xd65f03c0 // ret

	// LBB1_148:
	WORD $0xd2800010 // mov	x16, #0

	// LBB1_149:
	WORD $0x8b0d0208 // add	x8, x16, x13
	WORD $0xcb080028 // sub	x8, x1, x8
	WORD $0xaa0803e0 // mov	x0, x8
	WORD $0xa9424ff4 // ldp	x20, x19, [sp, #32]
	WORD $0xa94157f6 // ldp	x22, x21, [sp, #16]
	WORD $0xa8c35ff8 // ldp	x24, x23, [sp], #48
	WORD $0xd65f03c0 // ret

	// _TabEncodeCharsetStd:
	DWORD $0x4847464544434241
	DWORD $0x504f4e4d4c4b4a49
	DWORD $0x5857565554535251
	DWORD $0x6665646362615a59
	DWORD $0x6e6d6c6b6a696867
	DWORD $0x767574737271706f
	DWORD $0x333231307a797877
	DWORD $0x2f2b393837363534

	// _TabEncodeCharsetURL:
	DWORD $0x4847464544434241
	DWORD $0x504f4e4d4c4b4a49
	DWORD $0x5857565554535251
	DWORD $0x6665646362615a59
	DWORD $0x6e6d6c6b6a696867
	DWORD $0x767574737271706f
	DWORD $0x333231307a797877
	DWORD $0x5f2d393837363534

	// _VecDecodeCharsetStd:
	DWORD $0xffffffffffffffff
	DWORD $0xffffffffffffffff
	DWORD $0xffffffffffffffff
	DWORD $0xffffffffffffffff
	DWORD $0xffffffffffffffff
	DWORD $0x3fffffff3effffff
	DWORD $0x3b3a393837363534
	DWORD $0xffffffffffff3d3c
	DWORD $0x6050403020100ff
	DWORD $0xe0d0c0b0a090807
	DWORD $0x161514131211100f
	DWORD $0xffffffffff191817
	DWORD $0x201f1e1d1c1b1aff
	DWORD $0x2827262524232221
	DWORD $0x302f2e2d2c2b2a29
	DWORD $0xffffffffff333231
	DWORD $0xffffffffffffffff
	DWORD $0xffffffffffffffff
	DWORD $0xffffffffffffffff
	DWORD $0xffffffffffffffff
	DWORD $0xffffffffffffffff
	DWORD $0xffffffffffffffff
	DWORD $0xffffffffffffffff
	DWORD $0xffffffffffffffff
	DWORD $0xffffffffffffffff
	DWORD $0xffffffffffffffff
	DWORD $0xffffffffffffffff
	DWORD $0xffffffffffffffff
	DWORD $0xffffffffffffffff
	DWORD $0xffffffffffffffff
	DWORD $0xffffffffffffffff
	DWORD $0xffffffffffffffff

	// _VecDecodeCharsetURL:
	DWORD $0xffffffffffffffff
	DWORD $0xffffffffffffffff
	DWORD $0xffffffffffffffff
	DWORD $0xffffffffffffffff
	DWORD $0xffffffffffffffff
	DWORD $0xffff3effffffffff
	DWORD $0x3b3a393837363534
	DWORD $0xffffffffffff3d3c
	DWORD $0x6050403020100ff
	DWORD $0xe0d0c0b0a090807
	DWORD $0x161514131211100f
	DWORD $0x3fffffffff191817
	DWORD $0x201f1e1d1c1b1aff
	DWORD $0x2827262524232221
	DWORD $0x302f2e2d2c2b2a29
	DWORD $0xffffffffff333231
	DWORD $0xffffffffffffffff
	DWORD $0xffffffffffffffff
	DWORD $0xffffffffffffffff
	DWORD $0xffffffffffffffff
	DWORD $0xffffffffffffffff
	DWORD $0xffffffffffffffff
	DWORD $0xffffffffffffffff
	DWORD $0xffffffffffffffff
	DWORD $0xffffffffffffffff
	DWORD $0xffffffffffffffff
	DWORD $0xffffffffffffffff
	DWORD $0xffffffffffffffff
	DWORD $0xffffffffffffffff
	DWORD $0xffffffffffffffff
	DWORD $0xffffffffffffffff
	DWORD $0xffffffffffffffff

TEXT ·__b64decode(SB), NOSPLIT | NOFRAME, $0 - 40
	NO_LOCAL_POINTERS

_entry:
	MOVD 16(g), R16
	SUB  $48, RSP, R17
	CMP  R16, R17
	BLS  _stack_grow

_b64decode:
	MOVD out+0(FP), R0
	MOVD src+8(FP), R1
	MOVD len+16(FP), R2
	MOVD mode+24(FP), R3
	MOVD ·_subr__b64decode(SB), R4
	MOVD R29, R19
	MOVD R30, R20
	CALL (R4)
	MOVD R0, ret+32(FP)
	MOVD R20, R30
	MOVD R19, R29
	RET

_stack_grow:
	MOVD R30, R3
	CALL runtime·morestack_noctxt<>(SB)
	JMP  _entry

TEXT ·__b64encode(SB), NOSPLIT | NOFRAME, $0 - 24
	NO_LOCAL_POINTERS

_b64encode:
	MOVD out+0(FP), R0
	MOVD src+8(FP), R1
	MOVD mode+16(FP), R2
	MOVD ·_subr__b64encode(SB), R3
	JMP  (R3)
